dev:
  url: "https://test.com/"
  login: "test@gmail.com"
  password: "test"
stage:
  url: "https://stage.test.com"
  login: "test@gmail.com"
  password: "testthis"
prod:
  url: "https://app.test.com"
  login: "test@gmail.com"
  password: "testthis"
