dev:
  url: "https://dev.cameraiq.com/"
  login: "oaverkin@provectus.com"
  password: "L&00sa53oa"
stage:
  url: "https://stage.cameraiq.com"
  login: "oaverkin@provectus.com"
  password: "A!11edwsqa11"
prod:
  url: "https://app.cameraiq.com"
  login: "oaverkin@provectus.com"
  password: "A!11edwsqa11"
