version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo pip install -r requirements.txt
            sudo npm install -g allure-commandline --save-dev
      - run:
          name: run tests
          command: |
            pytest -n 3 --dist=loadscope -v --reruns 2 --alluredir  ./allure-results tests/ --junitxml="result.xml"
      - run:
          name: run report
          when: always
          command: |
            allure generate -c
      - store_artifacts:
          path: allure-report
          destination: allure-report
          when: always
      - store_test_results:
          path: result.xml